### ISSUE TITLE
[style] i need to enhance the readme file

### ISSUE THREAD

**Issue by anshulsoni4** [zeabur/zbpack#110]
### What's the style idea?

improve readme file 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pan93412** [comment]
go ahead! 💯

**Comment by anshulsoni4** [comment]
> go ahead! 💯

gssoc tag ?

**Comment by MichaelYuhe** [comment]
> > go ahead! 💯
> 
> gssoc tag ?

I've added the tag for you!

**Comment by anshulsoni4** [comment]
> > > go ahead! 💯
> > 
> > 
> > gssoc tag ?
> 
> I've added the tag for you!

alright thanks

**Comment by anshulsoni4** [comment]
ok
