### ISSUE TITLE
[bug] Gleam docker is still using Gleam 1.0

### ISSUE THREAD

**Issue by JLarky** [zeabur/zbpack#325]
### Describe the bug

I just got this error when trying to build my app:

```
#10 13.50 The package `mist` requires a Gleam version satisfying >= 1.2.0 but you are using v1.0.0.
```

It [looks like](https://github.com/zeabur/zbpack/blob/0ff44c514d54dbe5b5827208deceb80892b866cd/internal/gleam/gleam.go#L11) that Gleam docker is still on Gleam 1.0 and I don't know if there's a way to update it on my end somehow :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pan93412** [comment]
Thanks for your report! I have opened a PR to fix it.
