### ISSUE TITLE
[feature] Allow to set specific Bun version

### ISSUE THREAD

**Issue by jonaspm** [zeabur/zbpack#348]
### Is your feature request related to a problem? Please describe.

I want to set latest Bun version 1.1.27 as the runtime but the documentation does not state how to do it, `"engines"` property inside `package.json` does not work either.

### Describe the solution you'd like

```
{
  "engines": {
    "bun": "1.1.27"
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pan93412** [comment]
Good idea. Let me investigate later.

**Comment by jonaspm** [comment]
Related Bun open issue: https://github.com/oven-sh/bun/issues/5846
