### ISSUE TITLE
[Feature Request] Support Umi API Route build and deployment like Next.js

### ISSUE THREAD

**Issue by dengfuping** [zeabur/zbpack#361]
### Is your feature request related to a problem? Please describe.

- Umi API Route: https://umijs.org/blog/develop-blog-using-umi#%E5%AE%9E%E7%8E%B0-api-%E8%B7%AF%E7%94%B1

### Describe the solution you'd like

- Umi API Route could deploy in Vercel:

![image](https://github.com/user-attachments/assets/09e37ae4-4391-4052-8363-d95e6e0c5d15)

- Sample demo: https://github.com/dengfuping/oceanbase-playground

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pan93412** [comment]
I’ve never tried Umi, and I would really appreciate it if you could contribute this feature! :)

**Comment by pan93412** [comment]
Serverless has been deprecated, sorry.
