### ISSUE TITLE
Allow zbpack to generate a Dockerfile without executing it

### ISSUE THREAD

**Issue by pan93412** [zeabur/zbpack#47]
Link: https://linear.app/zeabur/issue/ZEA-656

The Command-Line Interface of zbpack always builds the image without printing the Dockerfile artifact. I propose to add a new flag, `--dry-run` or `--print` to print out the artifacts to a directory.

```plain
$ zbpack --output-only (somewhere) /somewhere
$ ls somewhere
Dockerfile zeabur.json
$ cat zeabur.json
{"type": "docker", "path": ["Dockerfile"]}
$ cat Dockerfile
FROM alpine
CMD echo "This is awful, I won't touch it"
```

Note that, Zbpack not only has the function of generating Dockerfile, but also needs to consider other types of output, such as:

-  Which resources can be turned into static resources: handling requests with what kind of paths (regex).
-  Which requests should be dynamic.
-  What is the format of the function? (AWS Lambda, CloudFlare Worker)

For example, the output of a pure static framework only consists of static files, which can be served using our OSS. For a "static + function" scenario, it may look like this:

```plan
$ tree somewhere
`---vercel 
       `---- output
`---meta.json
$ cat meta.json
{"type": "static", "path": [".vercel/output"]}
```

At present, the builder only has the function of running containers, but we hope that in the future it can achieve functions such as "putting static files into OSS".

**Comment by AishwaryaSatpute1** [comment]
I believe working on this enhancement will contribute to the overall functionality and flexibility of zbpack. Therefore, I kindly request that you assign me this issue so that I can start working on it.

**Comment by pan93412** [comment]
> I believe working on this enhancement will contribute to the overall functionality and flexibility of zbpack. Therefore, I kindly request that you assign me this issue so that I can start working on it.

Thanks for your contribution to Zbpack!
