### ISSUE TITLE
New Dockerfile template

### ISSUE THREAD

**Issue by pan93412** [zeabur/zbpack#49]
Link: https://linear.app/zeabur/issue/ZEA-655

We used to construct Dockerfile by string concatenation; however, it messes up the codebase and adds complexity to reviewing the Dockerfile artifact.

We have refactored the construction of Dockerfile in [nodejs](https://github.com/zeabur/zbpack/tree/main/internal/nodejs) and [rust](https://github.com/zeabur/zbpack/tree/main/internal/rust) with `text/template`. However, the other planners are currently not refactored yet, and we are finding someone to refactor them (not limited to `text/template`, you can also try something like `buildah`!)

**Comment by yuaanlin** [comment]
Maybe we can survey a new approach based on [Buildah](https://github.com/containers/buildah) ?

**Comment by i-am-yuvi** [comment]
I can try this, Can you please assign me to this?

**Comment by pan93412** [comment]
> I can try this, Can you please assign me to this?

It is better to complete your currently-assigned issue first! 🤣

**Comment by i-am-yuvi** [comment]
Sure @pan93412, actually there are very few projects in Golang and this one I found. So I was in a hurry to assign this to me.
No worries I will complete the previous ones😅
