### ISSUE TITLE
next: use standalone server to minimize the docker image size

### ISSUE THREAD

**Issue by pan93412** [zeabur/zbpack#50]
Link: https://linear.app/zeabur/issue/ZEA-779

- Bundle the Next.js app with [the standalone server](https://nextjs.org/docs/pages/api-reference/next-config-js/output) to lightweight the image size and the resource footprint.
- We don't help user enable the standalone server – but we pick standalone server when user enables it.
- Determine if this project enables standalone server by checking the `.next` directory (`next.config.js` may be scattered in monorepos)
- Write this logic in `Dockerfile` or on planning (better but harder).

**Comment by i-am-yuvi** [comment]
I think I can do this, kindly assign me to this

**Comment by yuaanlin** [comment]
This issue is no longer needed because zbpack can build Next.js project into serverless format.
