### ISSUE TITLE
Run a regression test (snapshot test) for zbpack

### ISSUE THREAD

**Issue by pan93412** [zeabur/zbpack#52]
Link: https://linear.app/zeabur/issue/ZEA-657

> Regression testing (rarely, non-regression testing) is re-running [functional](https://www.wikiwand.com/en/Functional_testing) and [non-functional tests](https://www.wikiwand.com/en/Non-functional_testing) to ensure that previously developed and tested software still performs as expected after a change. If not, that would be called a [regression](https://www.wikiwand.com/en/Software_regression). (Wikipedia, 2023)

The folder structure of the regression test can be like this:

```
-- zbpack (root)
 `- tests
  `- zea123-python-bug
   `- main.py
   `- requirements.txt
   `- expected.Dockerfile  <-- the working dockerfile
```

When the Dockerfile changes unexpectedly, it must be found in CI:

```
expected: ...
actual:   ...
diff:
  + ...
  - ...
```

**Comment by oshinsaraf** [comment]
Can you assign me this under GSSOC'23?

**Comment by MichaelYuhe** [comment]
> Can you assign me this under GSSOC'23?

I've assigned this issue to you
