### ISSUE TITLE
Add Solid.js support

### ISSUE THREAD

**Issue by pan93412** [zeabur/zbpack#53]
Link: https://linear.app/zeabur/issue/ZEA-415

It should be added in the `nodejs` planner.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23,

**Comment by anshumanjaiswal** [comment]
Hey @MichaelYuhe can you please describe this issue because I want to work on this. Comes under GSSOC'23
