### ISSUE TITLE
Support PDM

### ISSUE THREAD

**Issue by pan93412** [zeabur/zbpack#54]
Link: https://linear.app/zeabur/issue/ZEA-650

It should be in the `python` planner.

- It is hard to determine if this project uses `poerty` or `pdm` without parsing `pyproject.yaml`.

**Comment by ScmTble** [comment]
Is it possible to judge whether it is pdm or poetry based on the lock file?
- pdm： pdm.lock
- poerty: poerty.lock

**Comment by pan93412** [comment]
> Is it possible to judge whether it is pdm or poetry based on the lock file?
> 
> * pdm： pdm.lock
> * poerty: poerty.lock

Not a bad approach! However, it is better to determine by checking the sections in `pyproject.toml`. Poetry has [`tool.poetry`](https://python-poetry.org/docs/pyproject/ ) while PDM has [`tool.pdm`](https://github.com/pdm-project/pdm/blob/main/pyproject.toml#L59).

**Comment by ScmTble** [comment]
Should the Python version be checked? It is now fixed @pan93412

**Comment by pan93412** [comment]
Great to check that! Can I assign this issue to you if you are interested in this topic?

**Comment by ScmTble** [comment]
Yes i can try! thank you
