### ISSUE TITLE
Improving the readme file 

### ISSUE THREAD

**Issue by harshsingh32** [zeabur/zbpack#56]
I would like to work on improving the readme file of this project making it engaging for the users and make it more expressive.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by MichaelYuhe** [comment]
How do you plan to improve it?

**Comment by harshsingh32** [comment]
Adding more expressive information about the project that engage the user to contribute to the project.

**Comment by itsalicelee** [comment]
Thanks @harshsingh32! 🤩 If you encounter any problems, feel free to contact us.
