### ISSUE TITLE
.NET support

### ISSUE THREAD

**Issue by MichaelYuhe** [zeabur/zbpack#64]
We are looking for a new contributor to help us add .NET support in zbpack.

Zeabur doesn's support [.NET](https://learn.microsoft.com/en-us/dotnet/csharp/) services now, but as a great programming language, some users may want to deploy .NET services on Zeabur.

If you have any questions or need help getting started, feel free to reach out to us in our [Discord server.](https://discord.gg/DrdGCvXEyY) We are happy to provide guidance and support.

**Comment by absundr** [comment]
Hey, I've got some .NET experience. You can assign this to me and I'll take a look.

**Comment by yuaanlin** [comment]
@absundr, could you create a template repository as an example to demonstrate how a .NET project can be deployed on Zeabur using zbpack?

Just like 
https://github.com/zeabur/gin-template
https://github.com/zeabur/axum-template
https://github.com/zeabur/rails-template

**Comment by absundr** [comment]
@yuaanlin Sounds good. Can you create the repository and I'll commit the samples to it?

**Comment by yuaanlin** [comment]
> @yuaanlin Sounds good. Can you create the repository and I'll commit the samples to it?

There you go 🚀 https://github.com/zeabur/dotnet-template

**Comment by absundr** [comment]
@yuaanlin awesome, thanks! can I add multiple templates to the repo or is it set up in a way that it should contain just one template?

**Comment by absundr** [comment]
btw, I can't seem to fork the repo because it's empty. Perhaps if you could add a readme file it should work?

**Comment by yuaanlin** [comment]
> btw, I can't seem to fork the repo because it's empty. Perhaps if you could add a readme file it should work?

@absundr My fault. I have added the readme file. You should be able to fork it now.

> Can I add multiple templates to the repo or is it set up in a way that it should contain just one template?

This repo will be deployed on Zeabur directly so it should not contains many templates in a single repo. Can you give me the name of other template you want to create? Let me create repos for you!

**Comment by absundr** [comment]
> This repo will be deployed on Zeabur directly so it should not contains many templates in a single repo. Can you give me the name of other template you want to create? Let me create repos for you!

Okay, I have created samples for blazor, mvc, asp.net web app and web api. Let me know which ones you want to add. 

Which template do you want me to add to the current `dotnet-template` repo?

**Comment by yuaanlin** [comment]
> Which template do you want me to add to the current `dotnet-template` repo?

@absundr What about we create 4 repos:

- `blazor-template`
- `dotnet-mvc-template`
- `asp-dotnet-web-app-template`
- `asp-dotnet-web-api-template`

(If you think there is other name more suitable for the template, please let me know. I am not familiar with ASP.NET ecosystem 😂)

**Comment by yuaanlin** [comment]
@absundr There you go!

https://github.com/zeabur/blazor-template
https://github.com/zeabur/dotnet-mvc-template
https://github.com/zeabur/asp-dotnet-web-app-template
https://github.com/zeabur/asp-dotnet-web-api-template
