### ISSUE TITLE
Printing the docker run command for dotnet apps

### ISSUE THREAD

**Issue by absundr** [zeabur/zbpack#66]
## Context
zbpack will print the generic `docker run -p 8080:8080 -it <docker-image>` after docker image is built but this command does not work for dotnet apps.

## Proposal
For dotnet apps, the port is configured under `Properties/launchSettings.json`, it needs to get the port from this file and then generate a docker run command.

**Comment by absundr** [comment]
Hi, you can assign this to me. Thanks!

**Comment by MichaelYuhe** [comment]
> Hi, you can assign this to me. Thanks!

OK I've assigned this to you. Thanks for finding this issue.

**Comment by absundr** [comment]
@MichaelYuhe Do you have a requirement to run the docker command internally? Or just printing it to the terminal is enough?

**Comment by MichaelYuhe** [comment]
> @MichaelYuhe Do you have a requirement to run the docker command internally? Or just printing it to the terminal is enough?

I think just priting to terminal is fine. @pan93412 @yuaanlin What do you think?

**Comment by yuaanlin** [comment]
Hi @absundr , actually we ask all service running on Zeabur should listen on port in environment variable `$PORT`.

Is this feasible for .NET service? Or it only accept a hard coded port in the config?

**Comment by yuaanlin** [comment]
> I did some research and it is possible to configure the port. Though, I have a question. Where is the $PORT variable coming from and is this variable resolved during the docker image build or when you start the container?

@absundr The `$PORT` environment variable is dynamically injected during the container **starting process** by Zeabur.

**Comment by absundr** [comment]
@yuaanlin Do you know how I can test it locally? I've added these lines to the Dockerfile

```
EXPOSE $PORT
ENV ASPNETCORE_URLS=http://+:$PORT
```

This should ideally configure the port but the problem I'm having is getting the value of `$PORT` injected into the Dockerfile. Technically, the Dockerfile is executed just once when the image is built, so I'm wondering how it would work to inject the env variables during runtime?

**Comment by yuaanlin** [comment]
> 
> ```
> EXPOSE $PORT
> ENV ASPNETCORE_URLS=http://+:$PORT
> ```
> 
> This should ideally configure the port but the problem I'm having is getting the value of `$PORT` injected into the Dockerfile. Technically, the Dockerfile is executed just once when the image is built, so I'm wondering how it would work to inject the env variables during runtime?

I think this is not working because you cannot use a runtime variable in the Dockerfile. Can .NET dynamically get the environment variable in start process?

**Comment by yuaanlin** [comment]
@absundr For example, in the Node.js project, we don't need to modify the Dockerfile (no `EXPOSE` needed!) but we require user's code should listen on `$PORT`:

```js
app.listen(process.env.PORT || 3000);
```

**Comment by absundr** [comment]
> > ```
> > EXPOSE $PORT
> > ENV ASPNETCORE_URLS=http://+:$PORT
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This should ideally configure the port but the problem I'm having is getting the value of `$PORT` injected into the Dockerfile. Technically, the Dockerfile is executed just once when the image is built, so I'm wondering how it would work to inject the env variables during runtime?
> 
> I think this is not working because you cannot use a runtime variable in the Dockerfile. Can .NET dynamically get the environment variable in start process?

Yes, there are a few different ways to configure the port but I think to get the container to listen on a port other than 80, we need to specify `ASPNETCORE_URLS` in the Dockerfile.

> @absundr For example, in the Node.js project, we don't need to modify the Dockerfile (no `EXPOSE` needed!) but we require user's code should listen on `$PORT`:
> 
> ```js
> app.listen(process.env.PORT || 3000);
> ```

Isn't this altering the source code of the project and is that a good approach? 



> If `ASPNETCORE_URLS` is the only way to run .NET app on specify port, maybe we can just use `8080` for now.

@yuaanlin Either way, let me spend some more time on it and see if I can configure the port dynamically. Otherwise, I'll hardcode it.

**Comment by absundr** [comment]
@yuaanlin Okay, there is another way we can force the app to listen on a port we want. 

```
var builder = WebApplication.CreateBuilder(args);
builder.WebHost.UseUrls("http://*:" + Environment.GetEnvironmentVariable("PORT"));
```

Adding these lines to the `Program.cs` does the trick, but I'm still unsure if this would be good practice since we are altering the source code.  Another complication I see is that the variable `builder` is named by the user and if we added the `UseUrls` line we need to know the exact name provided by the user. (It can be configured in a few different ways, it's not always done like this. It's something we need to account for) 

Let me know what you think or if you have suggestions, Thanks!

**Comment by yuaanlin** [comment]
> ```
> var builder = WebApplication.CreateBuilder(args);
> builder.WebHost.UseUrls("http://*:" + Environment.GetEnvironmentVariable("PORT"));
> ```
> 
> Adding these lines to `Program.cs` does the trick, but I'm still unsure if this would be good practice since we are altering the source code. Another complication I see is that the variable `builder` is named by the user and if we added the `UseUrls` line we need to know the exact name provided by the user. (It can be configured in a few different ways, it's not always done like this. It's something we need to account for)
> 
> Let me know what you think or if you have suggestions, Thanks!

I think we don't need to altering user's source code. We can just require users to follow our convention (listen on `$PORT`).
And we using the template repo to illustrate how can they deploy .NET service with the correct port!

**Comment by absundr** [comment]
> I think we don't need to altering user's source code. We can just require users to follow our convention (listen on `$PORT`). And we can using the template repos to illustrate how can they deploy .NET service with the correct port!

Great, I'll make the necessary changes then.
