### ISSUE TITLE
add readme badges

### ISSUE THREAD

**Issue by S-ishita** [zeabur/zbpack#71]
I want to add readme badges..please assign this issue to me

**Comment by MichaelYuhe** [comment]
What kind of badges? Could you find me some examples?

**Comment by S-ishita** [comment]
![badges](https://github.com/zeabur/zbpack/assets/104543751/ef7f2e04-f0b8-4a8b-be4d-94e2321e5897)

**Comment by pan93412** [comment]
Well… Sure.
