### ISSUE TITLE
Missing Issue Template

### ISSUE THREAD

**Issue by Anshika-Jain02** [zeabur/zbpack#75]
## Description:

*I noticed that the repository does not have an issue template. Having an issue template can greatly improve the clarity and consistency of issue reports, making it easier for contributors and maintainers to understand and address the problems or feature requests effectively*

## Here are three templates that I want to include:

*Issue Template: This template enables users to create well-structured issue reports by providing sections for a concise title, detailed description, steps to reproduce (if applicable), expected behavior, actual behavior, additional information, and environment details.*

*Feature Request Template: The feature request template allows users to outline their desired features with clarity, including sections for a clear feature description, expected benefits, and any additional context or information.*

*Documentation Template:  This template facilitates the creation of comprehensive documentation by providing a structured format, including sections for an introduction, usage instructions, examples, and other relevant details.*

**Please assign this issue to me under Gssoc'23 @yuaanlin**

**Comment by Aman-Singh-Kushwaha** [comment]
Hey @Anshika-Jain02 can I work on it now, If yes Please assign it to me

**Comment by Anshika-Jain02** [comment]
Hi @Aman-Singh-Kushwaha ryt now i am working on this issue. You can raise a similar issue on another project where it has not been raised and then you can work on it.
