### ISSUE TITLE
Docusaurus support

### ISSUE THREAD

**Issue by yuaanlin** [zeabur/zbpack#76]
It is good to have [Docusaurus](https://github.com/facebook/docusaurus) framework supported in the Node.js provider of zbpack.

**Comment by ScmTble** [comment]
I can try this, Can you please assign me to this?

**Comment by MichaelYuhe** [comment]
I've assigned this issue to you! 😄

**Comment by itsalicelee** [comment]
Thanks for the support @ScmTble 🚀 
The PR is merged:
https://github.com/zeabur/zbpack/pull/78
