### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by AnushkaKalra** [zeabur/zbpack#82]
Hi @yuaanlin 
I would like to improvize the documentation of readme.md file.

To complete the readme.md file, here are a few features I'd want to add:

1. Adding a detailed description of the programs the project has been a part of. eg: GSSoC'23
2. Adding "back to top" feature in readme.md file
3. Adding the owner id

@yuaanlin  Please assign me this issue under GSSoC'23 so that I can improvise and update Readme.md file.

**Comment by pan93412** [comment]
I think so. The current README file already expresses well. I don't think we need to add more project-unrelated information there.

I would prefer to reject this proposal; however, feel free to open other tickets and contribute this project 😉

**Comment by AnushkaKalra** [comment]
No issues, thank you! I'll try my best at contributions!
