### ISSUE TITLE
[feature] Enhancement of README file of Repository

### ISSUE THREAD

**Issue by MisterMickey** [zeabur/zbpack#89]
### Is your feature request related to a problem? Please describe.

It's not directly related to any problem but It's not appealing for the README to be all left-aligned and also only text is there and so emojis or stickers.

### Describe the solution you'd like

I would like to enhance the README by making its text centre aligned and adding some emojis/stickers with the headings to make the README more appealing and easy to understand.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by MichaelYuhe** [comment]
Thanks for your suggestion! But unfortunately we are not going to add stickers in our README file.
