### ISSUE TITLE
Addition of dependabot.yml file

### ISSUE THREAD

**Issue by DivyanshiNarang** [zeabur/zbpack#90]
We need to add dependabot.yml file as it helps us to keep our dependencies up to date. Every day, it checks your dependency files for outdated requirements and opens individual PRs for any it finds.

@zeabur please assign me this issue under gssoc'23.

**Comment by zengzzzzz** [comment]
By the way, I have added the `dependabot.yml` file for this. I would appreciate if you could review the pull request whenever you have some free time. Thank you!
